### ISSUE TITLE
We can't have a good prompt using `starship`

### ISSUE THREAD

**Issue by ccmywish** [ccmywish/rbenv-for-windows#4]
As the README says.

On Windows, `starship`'s `command` is really bad.

```toml
[custom.rbenv]
style = "fg:bright-yellow bold"      
command = "Write-Host 3.1"     # Or command = "ruby.exe -v"
when = true  
format = "[$output ]($style)"
```
The `command` takes very long, it's unbelievably slow.

**Comment by ccmywish** [comment]
On Windows, `starship`'s `command` is really bad.

```toml
[custom.rbenv]
style = "fg:bright-yellow bold"      
command = "Write-Host 3.1"     # Or command = "ruby.exe -v"
when = true  
format = "[$output ]($style)"
```
The `command` takes very long, it's unbelievably slow.
